### PR TITLE
chore: update examples to use registry

### PR DESCRIPTION
**Pull request by bharathkkb**
This is an automated PR, please review carefully before merging.

### CODE REVIEW

**Comment by danielcampagnolitg** [comment]
The README should also have the source property updated in the Usage examples

**Comment by bharathkkb** [comment]
@danielcampagnolitg thanks for the callout, updated

**Comment by danielcampagnolitg** [comment]
@bharathkkb no problems. One more change on the README source, `cloud-workflow` is now `cloud-workflows`

**Comment by bharathkkb** [comment]
Good catch! Fixed now

**Comment by bharathkkb** [comment]
int test failure is unrelated - @anaik91 you may want to add a retry case like https://github.com/GoogleCloudPlatform/solutionbuilder-terraform-google-bigquery/blob/0783e8885f0d5d2fdbfc674431bee061962124ed/test/integration/data_warehouse/data_warehouse_test.go#L29

**Pull request merged**
